# Generated by Django 5.2 on 2025-05-14 08:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ecomApp', '0002_alter_product_sale_price'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Order',
        ),
    ]
